### ISSUE TITLE
为什么打开什么数据都没有，连登陆都不行

### ISSUE THREAD

**Issue by zhaowweny** [SmallRuralDog/electron-vue-music#1]
打开软件只有原有的内容，其他一片空白，登录也没有反应。

**Comment by SmallRuralDog** [comment]
后端跑了吗，接口地址改了吗？

**Comment by zhaowweny** [comment]
有三个进程在运行，接口地址没改吧，我用的另外一个第三方客户端一直都是正常的，不知道是不是端口冲突了还是怎么的。

**Comment by zhaowweny** [comment]
我是直接下载你打包的软件使用的啊，接口好像没变啊

**Comment by zhaowweny** [comment]
@bibi7 不是自动启动的吗？？难道还要手动开启？我装了另外一个electron做的第三方客户端，打开就能用。

**Comment by SmallRuralDog** [comment]
@zhaowweny 你要先把后端跑起来！然后接口地址改成你的就可以了

**Comment by zhaowweny** [comment]
@SmallRuralDog 后端？难道我还要自己安装node环境？怎么这么麻烦啊。。。我用的其他electron做的播放器安装就能用了。😅

**Comment by SmallRuralDog** [comment]
@zhaowweny 后端已经集成

**Comment by zhaowweny** [comment]
@SmallRuralDog 😃坐等打包享用，UI看着好清爽。
