### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by 1-riverfish** [SmallRuralDog/electron-vue-music#3]
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/components/Playlist/index.vue
  Module not found: Error: Can't resolve 'Vuex' in '/home/linuxclub/electron-vue-music/src/renderer/components/Playlist'
   @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/components/Playlist/index.vue 4:0-32
   @ ./src/renderer/components/Playlist/index.vue
   @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/views/main.vue
   @ ./src/renderer/views/main.vue
   @ ./src/renderer/router/index.js
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

ubuntu 18.04

**Comment by 1-riverfish** [comment]
建议先更换一下npm源到淘宝

**Comment by 1-riverfish** [comment]
把/home/linuxclub/electron-vue-music/src/renderer/components/Playlist/index.js中的import {mapState} from 'Vuex'改成import {mapState} from 'vuex'之后可以打包，看起来没问题了，就是不知道为什么？还有一个问题就是，Dog-music安装之后有一些功能没办法使用，npm run dev 这一步是什么意思呢？十分感谢！！！

**Comment by SmallRuralDog** [comment]
@1-riverfish 已修复
